apiVersion: apps/v1
kind: Deployment
metadata:
  name: vitepress
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vitepress
  template:
    metadata:
      labels:
        app: vitepress
    spec:
      containers:
        - name: nginx
          image: nginx:latest
          volumeMounts:
            - name: html
              mountPath: /usr/share/nginx/html
      volumes:
        - name: html
          hostPath:
            path: /Users/suzhipeng/Business/jan-blog/docs/.vitepress/dist
---
apiVersion: v1
kind: Service
metadata:
  name: vitepress
spec:
  selector:
    app: vitepress
  ports:
    - name: http
      port: 80
      targetPort: 80
  type: ClusterIP
