#!/bin/bash

generate_tidb_sidebar_zh() {
    # 生成中文侧边栏
    local lang="zh"
    local yaml_file="/Users/aric/Database/askaric/docs/sidebar.yaml"
    local output_file="/Users/aric/Database/askaric/docs/.vitepress/sidebar_tidb_${lang}.js"
    
    tmp_file=$(mktemp)
    
    yq -o json $yaml_file | jq --arg lang "$lang" '
    .tidb | map(
        (.category["name-en"]) as $category_en
        | {
            text: (.category["name-"+$lang]),
            items: (.subcategories // [] | map(
                (.["name-en"]) as $subcategory_en
                | {
                    text: .["name-"+$lang],
                    items: (.subsubcategories // [] | map({
                        text: .["name-"+$lang],
                        link: "/\($lang)/work/tidb/\($category_en)/\($subcategory_en)/\(
                            .file | sub(".md$";""
                        ))"
                    }))
                }
            ))
        }
    )' > $tmp_file

    echo "// Auto-generated by sidebar_yaml.sh
export const tidbDocSideBarZh = $(cat $tmp_file)" > $output_file
    
    rm $tmp_file
    echo "TiDB ${lang} sidebar generated at $output_file"
}

generate_tidb_sidebar_en() {
    # 生成英文侧边栏
    local lang="en"
    local yaml_file="/Users/aric/Database/askaric/docs/sidebar.yaml"
    local output_file="/Users/aric/Database/askaric/docs/.vitepress/sidebar_tidb_${lang}.js"
    
    tmp_file=$(mktemp)
    
    yq -o json $yaml_file | jq --arg lang "$lang" '
    .tidb | map(
        (.category["name-en"] ) as $category_en
        | {
            text: (.category["name-"+$lang]),
            items: (.subcategories // [] | map(
                (.["name-en"] ) as $subcategory_en
                | {
                    text: .["name-"+$lang],
                    items: (.subsubcategories // [] | map({
                        text: .["name-"+$lang],
                        link: "/\($lang)/work/tidb/\($category_en)/\($subcategory_en)/\(
                            .["name-en"]  | sub(".md$";"")
                        )"
                    }))
                }
            ))
        }
    )' > $tmp_file

    echo "// Auto-generated by sidebar_yaml.sh
export const tidbDocSideBarEn = $(cat $tmp_file)" > $output_file
    
    rm $tmp_file
    echo "TiDB ${lang} sidebar generated at $output_file"
}

# 执行生成命令
generate_tidb_sidebar_zh # 生成中文
generate_tidb_sidebar_en # 生成英文
