name: TiDB 使用问题提问模板
description: 请按照以下结构详细填写问题，所有字段均为必填项，我们会尽快答复
labels: [tidb, question]
body:
  - type: markdown
    attributes:
      value: |
        ## 📌 请完整、详细填写以下信息，越详细越容易获得帮助 🙏

  - type: input
    id: title
    attributes:
      label: 问题标题
      placeholder: 请简洁地描述你的问题
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: 环境信息
      description: |
        例如：TiDB 版本、操作系统、部署方式（单机/集群）、集群规模等
      placeholder: |
        - TiDB 版本:
        - 操作系统:
        - 部署方式:
        - 集群规模:
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: 复现步骤
      description: 请详细描述问题的复现步骤
      placeholder: |
        1. ...
        2. ...
        3. ...
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: 期望行为
      description: 请描述你期望的正确结果或行为
      placeholder: 期望 TiDB 应该如何表现？
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: 实际行为
      description: 请描述实际发生了什么，和期望有何不同？
      placeholder: 实际遇到的问题和表现
    validations:
      required: true

  - type: textarea
    id: error_log
    attributes:
      label: 相关日志/报错信息
      description: 请粘贴相关日志或错误信息（如有截图请上传）
      placeholder: |
        例如：
        [202X-XX-XX XX:XX:XX] [ERROR] ...
    validations:
      required: true

  - type: textarea
    id: additional
    attributes:
      label: 补充信息
      description: 其他你认为有帮助的信息，或相关截图、配置文件等
    validations:
      required: true
