name: TiDB 使用问题提问模板
description: 请按照以下结构填写问题，我们会尽快答复
labels: [tidb, question]
body:
  - type: markdown
    attributes:
      value: |
        ## 📌 请按以下结构完整填写，越详细越容易获得帮助 🙏

  - type: input
    id: title
    attributes:
      label: 问题标题
      placeholder: 请简洁地描述你的问题

  - type: markdown
    attributes:
      value: |
        ---
        ### 🔍 问题描述

  - type: textarea
    id:description
    attributes:
      label: 请详细描述问题
      placeholder: 说明背景、期望行为、实际观察到的行为
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        ---
        ### 🧪 已尝试解决方法

  - type: textarea
    id:attempts
    attributes:
      label: 你尝试过什么？
      placeholder: 比如是否重启过服务、修改参数、升级组件等

  - type: markdown
    attributes:
      value: |
        ---
        ### 🧭 环境信息

  - type: input
    id:tidb_version
    attributes:
      label: TiDB 版本
      placeholder: 比如 v7.1.0

  - type: input
    id:deployment
    attributes:
      label: 部署方式
      placeholder: 本地部署 / 云上部署（请注明云平台）

  - type: input
    id:os
    attributes:
      label: 操作系统
      placeholder: 比如 Ubuntu 20.04、macOS 14、CentOS 7

  - type: markdown
    attributes:
      value: |
        ---
        ### 📎 附加信息（截图/日志）

  - type: textarea
    id:logs
    attributes:
      label: 附加信息
      placeholder: 可以贴出相关日志、截图或 Grafana 链接
