name: TiDB 使用问题提问模板
description: 请按照以下结构填写问题，我们会尽快答复
labels: [tidb, question]
body:
  - type: markdown
    attributes:
      value: |
        ## 📌 请按以下结构完整填写，越详细越容易获得帮助 🙏

  - type: input
    id: title
    attributes:
      label: 问题标题
      placeholder: 请简洁地描述你的问题
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        ---
        ### 🔍 问题描述
