alter table ps_agent_agr_flow drop column ID;
alter table ps_fleet_bizunit drop column ID;
alter table ps_fleet_bizunit_factor_group drop column ID;
alter table ps_fleet_bizunit_track drop column ID;
alter table ps_fleet_factor_group drop column ID;
alter table ps_motorcade_agr_flow drop column ID;
alter table ps_motorcade_core drop column ID;
alter table ps_motorcade_core_mid drop column ID;
alter table ps_motorcade_step_data drop column ID;
alter table ps_motorcare_conf_fee drop column ID;
alter table ps_motorcare_fcst drop column ID;
alter table ps_sglcar_bizunit drop column ID;
alter table ps_sglcar_bizunit_copy drop column ID;
alter table ps_sglcar_bizunit_factor_group drop column ID;
alter table ps_sglcar_bizunit_tmp drop column ID;
alter table ps_sglcar_factor_group drop column ID;
alter table ps_sglcar_fcst_flow drop column ID;
alter table ps_sglcar_result drop column ID;
alter table ps_sglcar_step_data drop column ID;
alter table ps_agent_agr_factor_group drop column ID;
alter table ps_agent_agr_factor_group_his drop column ID;
alter table ps_agent_bizunit drop column ID;
alter table ps_agent_bizunit_factor_group drop column ID;
alter table ps_agent_bizunit_factor_group_his drop column ID;
alter table ps_agent_bizunit_his drop column ID;
alter table ps_agent_bizunit_track drop column ID;
alter table ps_agent_conf_fee drop column ID;
alter table ps_agent_conf_fee_his drop column ID;
alter table ps_agent_fcst drop column ID;
alter table ps_agent_fcst_his drop column ID;
alter table ps_agent_step_data drop column ID;
alter table ps_agent_step_data_his drop column ID;
alter table ps_bizunit_track drop column ID;
alter table ps_fleet_bizunit_factor_group_his drop column ID;
alter table ps_fleet_bizunit_his drop column ID;
alter table ps_fleet_bizunit_track_his drop column ID;
alter table ps_fleet_factor_group_his drop column ID;
alter table ps_motorcade_core_his drop column ID;
alter table ps_motorcade_core_mid_his drop column ID;
alter table ps_motorcade_step_data_his drop column ID;
alter table ps_motorcare_conf_fee_his drop column ID;
alter table ps_motorcare_fcst_his drop column ID;
alter table ps_sglcar_carty_selected_status drop column ID;
alter table ps_sglcar_carty_set drop column ID;
alter table ps_sglcar_carty_target drop column ID;
alter table ps_sglcar_carty_total drop column ID;
alter table ps_sglcar_param_config drop column ID;
alter table ps_sglcar_selected_status drop column ID;
alter table attributionanalysis drop column ID;
alter table comm_brand_group_flow drop column ID;
alter table finance_channel_data_flow drop column ID;
alter table itf_many_dimensions_analyze drop column ID;
alter table recom_carty_factor drop column ID;
alter table si_simulation_adjust_autodiscountresult drop column ID;
alter table si_simulation_adjust_input drop column ID;
alter table si_simulation_adjust_lrateassist drop column ID;
alter table si_simulation_adjust_newoldassist drop column ID;
alter table si_simulation_adjust_newoldcarass drop column ID;
alter table si_simulation_adjust_param_config drop column ID;
alter table si_simulation_adjust_premassist drop column ID;
alter table si_simulation_adjust_yearresult drop column ID;
alter table si_simulation_adjust_discount drop column ID;
alter table si_simulation_adjust_forecast drop column ID;
alter table si_simulation_adjust_vehicle drop column ID;
alter table si_simulation_curdis drop column ID;
alter table si_simulation_curpre drop column ID;
alter table si_simulation_direct drop column ID;
alter table si_simulation_mid drop column ID;
alter table si_simulation_spedis drop column ID;
alter table ps_agent_agr_fl drop column ID;
alter table ps_agent_bizunit_track_his drop column ID;
alter table fp_feeplan_carty_flow drop column ID;
alter table fp_feeplan_chan_flow drop column ID;
alter table si_simulation_spedis_mid drop column ID;
alter table ps_agent_agr drop column ID;


alter table ps_agent_agr rename column ID_TiDB to ID;
alter table ps_agent_agr_flow rename column ID_TiDB to ID;
alter table ps_fleet_bizunit rename column ID_TiDB to ID;
alter table ps_fleet_bizunit_factor_group rename column ID_TiDB to ID;
alter table ps_fleet_bizunit_track rename column ID_TiDB to ID;
alter table ps_fleet_factor_group rename column ID_TiDB to ID;
alter table ps_motorcade_agr_flow rename column ID_TiDB to ID;
alter table ps_motorcade_core rename column ID_TiDB to ID;
alter table ps_motorcade_core_mid rename column ID_TiDB to ID;
alter table ps_motorcade_step_data rename column ID_TiDB to ID;
alter table ps_motorcare_conf_fee rename column ID_TiDB to ID;
alter table ps_motorcare_fcst rename column ID_TiDB to ID;
alter table ps_sglcar_bizunit rename column ID_TiDB to ID;
alter table ps_sglcar_bizunit_copy rename column ID_TiDB to ID;
alter table ps_sglcar_bizunit_factor_group rename column ID_TiDB to ID;
alter table ps_sglcar_bizunit_tmp rename column ID_TiDB to ID;
alter table ps_sglcar_factor_group rename column ID_TiDB to ID;
alter table ps_sglcar_fcst_flow rename column ID_TiDB to ID;
alter table ps_sglcar_result rename column ID_TiDB to ID;
alter table ps_sglcar_step_data rename column ID_TiDB to ID;
alter table ps_agent_agr_factor_group rename column ID_TiDB to ID;
alter table ps_agent_agr_factor_group_his rename column ID_TiDB to ID;
alter table ps_agent_bizunit rename column ID_TiDB to ID;
alter table ps_agent_bizunit_factor_group rename column ID_TiDB to ID;
alter table ps_agent_bizunit_factor_group_his rename column ID_TiDB to ID;
alter table ps_agent_bizunit_his rename column ID_TiDB to ID;
alter table ps_agent_bizunit_track rename column ID_TiDB to ID;
alter table ps_agent_conf_fee rename column ID_TiDB to ID;
alter table ps_agent_conf_fee_his rename column ID_TiDB to ID;
alter table ps_agent_fcst rename column ID_TiDB to ID;
alter table ps_agent_fcst_his rename column ID_TiDB to ID;
alter table ps_agent_step_data rename column ID_TiDB to ID;
alter table ps_agent_step_data_his rename column ID_TiDB to ID;
alter table ps_bizunit_track rename column ID_TiDB to ID;
alter table ps_fleet_bizunit_factor_group_his rename column ID_TiDB to ID;
alter table ps_fleet_bizunit_his rename column ID_TiDB to ID;
alter table ps_fleet_bizunit_track_his rename column ID_TiDB to ID;
alter table ps_fleet_factor_group_his rename column ID_TiDB to ID;
alter table ps_motorcade_core_his rename column ID_TiDB to ID;
alter table ps_motorcade_core_mid_his rename column ID_TiDB to ID;
alter table ps_motorcade_step_data_his rename column ID_TiDB to ID;
alter table ps_motorcare_conf_fee_his rename column ID_TiDB to ID;
alter table ps_motorcare_fcst_his rename column ID_TiDB to ID;
alter table ps_sglcar_carty_selected_status rename column ID_TiDB to ID;
alter table ps_sglcar_carty_set rename column ID_TiDB to ID;
alter table ps_sglcar_carty_target rename column ID_TiDB to ID;
alter table ps_sglcar_carty_total rename column ID_TiDB to ID;
alter table ps_sglcar_param_config rename column ID_TiDB to ID;
alter table ps_sglcar_selected_status rename column ID_TiDB to ID;
alter table attributionanalysis rename column ID_TiDB to ID;
alter table comm_brand_group_flow rename column ID_TiDB to ID;
alter table finance_channel_data_flow rename column ID_TiDB to ID;
alter table itf_many_dimensions_analyze rename column ID_TiDB to ID;
alter table recom_carty_factor rename column ID_TiDB to ID;
alter table si_simulation_adjust_autodiscountresult rename column ID_TiDB to ID;
alter table si_simulation_adjust_input rename column ID_TiDB to ID;
alter table si_simulation_adjust_lrateassist rename column ID_TiDB to ID;
alter table si_simulation_adjust_newoldassist rename column ID_TiDB to ID;
alter table si_simulation_adjust_newoldcarass rename column ID_TiDB to ID;
alter table si_simulation_adjust_param_config rename column ID_TiDB to ID;
alter table si_simulation_adjust_premassist rename column ID_TiDB to ID;
alter table si_simulation_adjust_yearresult rename column ID_TiDB to ID;
alter table si_simulation_adjust_discount rename column ID_TiDB to ID;
alter table si_simulation_adjust_forecast rename column ID_TiDB to ID;
alter table si_simulation_adjust_vehicle rename column ID_TiDB to ID;
alter table si_simulation_curdis rename column ID_TiDB to ID;
alter table si_simulation_curpre rename column ID_TiDB to ID;
alter table si_simulation_direct rename column ID_TiDB to ID;
alter table si_simulation_mid rename column ID_TiDB to ID;
alter table si_simulation_spedis rename column ID_TiDB to ID;
alter table ps_agent_agr_fl rename column ID_TiDB to ID;
alter table ps_agent_bizunit_track_his rename column ID_TiDB to ID;
alter table fp_feeplan_carty_flow rename column ID_TiDB to ID;
alter table fp_feeplan_chan_flow rename column ID_TiDB to ID;
alter table si_simulation_spedis_mid rename column ID_TiDB to ID;