name: Build and Deploy VitePress Blog

on:
  push:
    branches:
      - main  # 或您的默认分支
  pull_request:
    branches:
      - main  # 或您的默认分支

jobs:
  build:
    name: Build and Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'  # 设置 Node.js 版本

      - name: Install dependencies using Yarn
        run: |
          yarn install

      - name: Build VitePress
        run: |
          yarn docs:build  # 使用正确的构建命令 docs:build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_dir: ./docs/.vitepress/dist  # VitePress 构建输出目录
          cname: 'www.askaric.com'  # 如果使用自定义域名，填入这里
